### ISSUE TITLE
;banga list bug

### ISSUE THREAD

**Issue by HariboDev** [MikeDev96/lucille-bot#102]
When someone bangas a song and then removes the song from their bangas, the song is still in the DB and therefore shows nobody:
![image](https://user-images.githubusercontent.com/57939433/97168660-b7182e00-1780-11eb-9867-0ba542ccd468.png)
Suggest a check when someone removes a song from their banga list to check if they're the last person and if so removes the song from the DB entirely.

**Comment by hlacannon** [comment]
@MikeDev96 @JWK95

**Comment by HariboDev** [comment]
@JWK95

**Comment by Deff3x** [comment]
@HariboDev You got the repo
