### ISSUE TITLE
Music commands shouldn't work when not in a server

### ISSUE THREAD

**Issue by Deff3x** [MikeDev96/lucille-bot#133]
You shouldn't be able to use any music commands when the user is not present in a server.

For example: I was all alone in the server and all of a sudden the bot joined scared the shit out of me and now I'm considering sueing Jue.

**Comment by MikeDev96** [comment]
You've got the repo.

**Comment by JoeC7756** [comment]
> You've got the repo.

+1

**Comment by Deff3x** [comment]
Blacklisted github until its fixed.

**Comment by JoeC7756** [comment]
https://github.com/MikeDev96/lucille-bot/commit/b521cc22eca00b418e54d3fd17fc5e8a7f334b72
