### ISSUE TITLE
Reddit ripper doesn't work on first use

### ISSUE THREAD

**Issue by MikeDev96** [MikeDev96/lucille-bot#162]
Reproduce:
1. Start bot
2. Paste Reddit link
3. Be sad

If you save the html to a file and look at it you will see there's a 503 error (I think it's 503) - only happens on the first use. Works fine if you paste the link again.

@JoeC7756 This sounds like a you issue ;)

**Comment by JoeC7756** [comment]
See https://github.com/MikeDev96/lucille-bot/pull/163

**Comment by MikeDev96** [comment]
> See #163

Thanks Jueeeeeeee <3
