### ISSUE TITLE
Implement webhook in to workflow

### ISSUE THREAD

**Issue by MikeDev96** [MikeDev96/lucille-bot#22]
Post a message to Discord using a webhook to let users know the bot will be down.

**Comment by MikeDev96** [comment]
Also update readme with contributors,

**Comment by hlacannon** [comment]
Added discord notifications using webhooks for pre and post deploy stages in #30

**Comment by hlacannon** [comment]
Added discord notifications using webhook for pre and post deploy stages to null; discord in #33
