### ISSUE TITLE
Make the connect/disconnect sounds toggleable per server

### ISSUE THREAD

**Issue by Deff3x** [MikeDev96/lucille-bot#34]
As much as I love hearing about how much Harrison loves d*** I don't think my whole house does.

!sound c disable
!sound d disable

**Comment by MikeDev96** [comment]
@hlacannon

**Comment by hlacannon** [comment]
Iya @MikeDev96

**Comment by hlacannon** [comment]
> @hlacannon

Iya

**Comment by MikeDev96** [comment]
You can now safely delete or rename the connect/disconnect sounds folders @Deff3x
