### ISSUE TITLE
Alias commands are all ran at the same time

### ISSUE THREAD

**Issue by MikeDev96** [MikeDev96/lucille-bot#48]
When running an alias command, all the commands are ran at the same time after 2 seconds.
Use the index param provided by forEach to multiply the timeout duration.
https://github.com/MikeDev96/lucille-bot/blob/50849a335410de417235c354f87ad832f4fd94da/commands/fun/alias.js#L71
@JoeC7756

**Comment by JoeC7756** [comment]
#61

**Comment by JoeC7756** [comment]
Close please @Deff3x
