### ISSUE TITLE
If banga list length is 0 output 'no bangers, what you playing at?' rather than a blank message

### ISSUE THREAD

**Issue by hlacannon** [MikeDev96/lucille-bot#69]
@MikeDev96 keef is adamant that its an enhancement not a bug :)

![image](https://user-images.githubusercontent.com/57939433/96112392-7267d980-0eda-11eb-9197-29ba7777d315.png)

**Comment by HendersonC20** [comment]
+ 1 for this enhancement

**Comment by JoeC7756** [comment]
+1
