### ISSUE TITLE
Add playing specific sound file from the sound command

### ISSUE THREAD

**Issue by JWK95** [MikeDev96/lucille-bot#77]
pls

**Comment by hlacannon** [comment]
You've got the repo

**Comment by JoeC7756** [comment]
https://github.com/MikeDev96/lucille-bot/commit/e89c226ed1e37d775eee36ead7dc081f585c9024

**Comment by MikeDev96** [comment]
Added in e89c226ed1e37d775eee36ead7dc081f585c9024
