### ISSUE TITLE
Connect 4 command registering win when you haven't won

### ISSUE THREAD

**Issue by JWK95** [MikeDev96/lucille-bot#89]
![image](https://user-images.githubusercontent.com/50180277/96574010-cef63a80-12c6-11eb-9ebf-1268f25091fa.png)

**Comment by hlacannon** [comment]
@Deff3x

**Comment by JWK95** [comment]
Miguls fault for rushed development

**Comment by Deff3x** [comment]
@JWK95 Not enough info.

What was your last move, how many games were active, why the fuck did i listen to migul.

**Comment by JWK95** [comment]
last move was column 1 row 3, no other games were active at the time, because he a bully

**Comment by Deff3x** [comment]
@JWK95 Mike fixed it himself

**Comment by MikeDev96** [comment]
Fixed in https://github.com/MikeDev96/lucille-bot/commit/e22a2911642392f872514829355a3509fd76e4ad
